---
version: "3.5"

networks:
  default:
    driver: bridge
    name: lab

services:
  gitlab:
    container_name: gitlab
    environment:
      # These settings will be evaluated on load - see
      # https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.demo.local/";
        prometheus_monitoring['enable'] = false;
    image: gitlab/gitlab-ce
    networks:
      default:
        aliases:
          - gitlab.demo.local
    ports:
      - "80:80"
      - "7722:22"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab

  jenkins:
    container_name: jenkins
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-scripts; script-src 'unsafe-inline'; style-src 'unsafe-inline';" # Allow inline JavaScript
      - PLUGINS_FORCE_UPGRADE=true # Enforce upgrade of native plugins at startup
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    image: jenkinsci/blueocean
    networks:
      default:
        aliases:
          - jenkins.demo.local
    ports:
      - "8080:8080"
      - "50000:50000" # for agent
    restart: unless-stopped
    # user: 1000:101 # jenkins:docker as the use needs to be able to start containers
    volumes:
      # - /etc/passwd:/etc/passwd:ro # Ensure that user can be found/mapped
      # - ~/jenkins:/home/jenkins:rw # Enables the jenkins user to write .ssh/known_hosts
      - ~/jenkins_home:/var/jenkins_home:rw # Workspace home
      - ~/jenkins-docker-certs:/certs/client:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro # Allows Jenkins to stop/start containers

  dockerhost:
    container_name: dind
    image: docker:dind
    privileged: true
    networks:
      default:
        aliases:
          - docker  # must be docker, otherwise get error: x509: certificate is valid for docker
    expose:
      - 2375
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ~/jenkins-docker-certs:/certs/client
      - ~/jenkins_home:/var/jenkins_home
    command: [ "dockerd-entrypoint.sh", "--insecure-registry=registry.demo.local:5000" ]

  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - registry.demo.local
    volumes:
      - registry:/var/lib/registry

  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.9-community
    networks:
      default:
        aliases:
          - sonarqube.demo.local
    ports:
      - "9000:9000"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  registry:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
